name: Run Analysis

# Controls when the action will run.
on:
  workflow_dispatch:
  pull_request:

jobs:
  build_and_run:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
        name: Checkout repo

      - name: Build container and download data
        uses: ./
        id: download-data
        with:
          args: OPENPEDCAN_URL=s3://d3b-openaccess-us-east-1-prd-pbta/open-targets/ OPENPEDCAN_RELEASE=testing bash download-data.sh

      - name: Run RUN-snv-frequencies in container
        uses: ./
        id: RUN-snv-frequencies
        with:
          args: bash analyses/snv-frequencies/run-snv-frequencies.sh
