name: Run Analysis

# Controls when the action will run.
on:
  workflow_dispatch:
  pull_request:

jobs:
  build_and_run:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
        name: Checkout repo

      - name: Run analysis in container
        uses: ./
        id: analysis
