name: Run Analysis

# Controls when the action will run.
on:
  workflow_dispatch:
  pull_request:
        branches: [ dev ]

jobs:
  build_and_download_data:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
        name: Checkout repo

# Build docker container and download testing data
      - name: Build container and download data
        uses: ./
        id: download-data
        with:
          args: OPENPEDCAN_URL=https://s3.amazonaws.com/d3b-openaccess-us-east-1-prd-pbta/open-targets OPENPEDCAN_RELEASE=testing bash download-data.sh

  run_analysis:
    runs-on: ubuntu-18.04
    needs: build_and_download_data
    steps:

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: myimage
          path: /tmp

      - name: Load Docker image
        run: |
          docker load --input /tmp/myimage.tar
          docker image ls -a

      - name: Run Molecular Subtyping - MB
        id: RUN-molecular-subtyping-MB
        run: |
            OPENPBTA_SUBSET=0 bash analyses/molecular-subtyping-MB/run-molecular-subtyping-mb.sh
