name: Analysis - Parallel

on:
  pull_request:
  workflow_dispatch:

jobs:
  run_analysis:
    name: Run Analysis - Parallel
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          # Molecular subtyping modules
          - name: Molecular Subtyping - MB
            entrypoint: molecular-subtyping-MB/run-molecular-subtyping-mb.sh
            openpbta_subset: 0

          - name: Molecular Subtyping - CHORDOMA
            entrypoint: molecular-subtyping-chordoma/run-molecular-subtyping-chordoma.sh
            openpbta_subset: 0

          - name: Molecular Subtyping - EWS
            entrypoint: molecular-subtyping-EWS/run_subtyping.sh

          - name: Molecular Subtyping - NEUROCYTOMA
            entrypoint: molecular-subtyping-neurocytoma/run_subtyping.sh

          - name: Molecular Subtyping - HGG
            entrypoint: molecular-subtyping-HGG/run-molecular-subtyping-HGG.sh
            
          - name: Molecular Subtyping - ATRT
            entrypoint: molecular-subtyping-ATRT/run-molecular-subtyping-ATRT.sh
            
          - name: Molecular Subtyping - PB
            entrypoint: molecular-subtyping-PB/run-molecular-subtyping-PB.sh
            
          - name: Molecular Subtyping - NBL
            entrypoint: molecular-subtyping-NBL/run-molecular-subtyping-NBL.sh

          - name: Molecular Subtyping - PATHOLOGY/COMPILE
            entrypoint: molecular-subtyping-pathology/run-subtyping-aggregation.sh
            openpbta_testing: 1

          - name: Molecular Subtyping - INTEGRATE (+ add cancer groups)
            entrypoint: molecular-subtyping-integrate/run-subtyping-integrate.sh
            

          # Analysis modules
          - name: Independent Specimens
            entrypoint: independent-samples/run-independent-samples.sh

          - name: Independent Specimens pre-release
            entrypoint: independent-samples/run-independent-samples.sh
            run_for_subtyping: 1

          - name: Fusion summary
            entrypoint: fusion-summary/run-new-analysis.sh
            openpbta_subset: 0

          - name: Consensus CN annotation
            entrypoint: focal-cn-file-preparation/run-prepare-cn.sh
            openpbta_testing: 1

          #- name: Immune Deconvolution
          #  entrypoint: immune-deconv/run-immune-deconv.sh

          #- name: EFO/MONDO annotation
          #  entrypoint: efo-mondo-mapping/run_search_and_qc.sh

          #- name: ENSEMBL Gene matching
          #  entrypoint: gene_match/run-gene-mapping.sh

          #- name: Update table annotation data
          #  entrypoint: long-format-table-utils/run-update-long-format-table-utils.sh

          #- name: RNA-Seq Expression Summary stats
          #  entrypoint: rna-seq-expression-summary-stats/run-rna-seq-expression-summary-stats.sh

          # MTP-specific modules
          #- name: Fusion frequency tables
          #  entrypoint: fusion-frequencies/run-frequencies.sh

          #- name: SNV frequency tables
          #  entrypoint: snv-frequencies/run-snv-frequencies.sh

          #- name: CNV frequency tables
          #  entrypoint: cnv-frequencies/run-cnv-frequencies-analysis.sh
            
          #- name: RNA-Seq batch correction
          #  entrypoint: rnaseq-batch-correct/run_ruvseq.sh

    steps:
      - uses: actions/checkout@v3

      - name: Download Data
        uses: docker://pgc-images.sbgenomics.com/d3b-bixu/open-pedcan:latest
        with:
          entrypoint: ./download-data.sh
        env:
          OPENPEDCAN_URL: https://s3.amazonaws.com/d3b-openaccess-us-east-1-prd-pbta/open-targets
          OPENPEDCAN_RELEASE: testing

      - name: Run Analysis
        uses: docker://pgc-images.sbgenomics.com/d3b-bixu/open-pedcan:latest
        with:
          entrypoint: analyses/${{ matrix.entrypoint }}
        env:
          OPENPBTA_SUBSET: ${{ matrix.openpbta_subset }}
          OPENPBTA_TESTING: ${{ matrix.openpbta_testing }}
          RUN_FOR_SUBTYPING: ${{ matrix.run_for_subtyping }}
          OPENPEDCAN_POLYA_STRAND: ${{ matrix.openpedcan_polya_strand }}